version: '3'

networks:
  app-net:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: 
      - "gunicorn"
      - "--conf"
      - "gunicorn_conf.py"
      - "--bind"
      - "0.0.0.0:8000"
      - "app:app"
    # volumes: 
    #   - ./pyproject.toml:/app/pyproject.toml
    #   - ./poetry.lock:/app/poetry.lock
    #   - ./uwsgi.ini:/app/uwsgi.ini
    #   - ./.env:/app/.env
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "curl -t 5 127.0.0.1:8000 | grep 'Server running' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

  nginx_backend:
    build:
      context: .
      dockerfile: DockerfileNginx
    ports:
      - 8010:80
    networks:
      - app-net
    # command: [nginx-debug, '-g', 'daemon off;']
    # volumes:
    #   - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    healthcheck:
      test: ["CMD-SHELL", "service nginx status || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
